//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfumeryApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodOfOrder
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public string GoodId { get; set; }
        public int Quantity { get; set; }
        public string GoodName
        {
            get { return this.Goods.Description; }
        }
        public virtual Goods Goods { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
