//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfumeryApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.GoodOfOrder = new HashSet<GoodOfOrder>();
        }
    
        public int Id { get; set; }
        public System.DateTime OrderDate { get; set; }
        public System.DateTime GetDate { get; set; }
        public int PointId { get; set; }
        public string Client { get; set; }
        public int Code { get; set; }
        public string Status { get; set; }
        public string Client1
        {
            get
            {
                if (this.Client == null)
                    return "Неизвестно";
                else
                    return this.Client;
            }
        }
        public string Point
        {
            get { return this.Points.Town + ", " + this.Points.Street + ", " + this.Points.Building; }
        }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoodOfOrder> GoodOfOrder { get; set; }
        public virtual Points Points { get; set; }
    }
}
